# Generated by Django 5.1.2 on 2024-11-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="expertise",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of programming languages or topics the tutor specializes in.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lesson_preferences",
            field=models.TextField(
                blank=True,
                help_text="Optional lesson preferences (e.g., desired programming language or specific focus).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("tutor", "Tutor"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
