# Generated by Django 5.1.2 on 2024-12-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('Unallocated', 'Unallocated'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled')], default='Unallocated', help_text='The current status of the lesson request.', max_length=20),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Write your message to the admin here')),
                ('reply', models.TextField(blank=True, default='', help_text='Admins reply to message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reply_timestamp', models.DateTimeField(blank=True, help_text="Timestamp of admin's reply", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
