# Generated by Django 5.1.2 on 2024-11-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_user_expertise_user_lesson_preferences_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="lesson_preferences",
        ),
    ]
