# Generated by Django 5.1.2 on 2024-12-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0002_lesson"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("tutor", "date", "time"), name="unique_tutor_schedule"
            ),
        ),
    ]
