# Generated by Django 5.1.2 on 2024-12-30 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0003_lesson_unique_tutor_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrequest",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("no_experience", "No Experience"),
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="no_experience",
                help_text="Describe your level of experience with this topic.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lessonrequest",
            name="requested_frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("fortnightly", "Fortnightly")],
                default="weekly",
                help_text="How often would you like lessons?",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lessonrequest",
            name="requested_topic",
            field=models.CharField(
                choices=[
                    ("python_programming", "Python Programming"),
                    ("web_development_with_js", "Web Development with JavaScript"),
                    ("ruby_on_rails", "Ruby on Rails"),
                    ("ai_and_ml", "AI and Machine Learning"),
                ],
                default="python_programming",
                help_text="What you would like to learn (e.g., Python, Rails, etc.).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lessonrequest",
            name="student",
            field=models.ForeignKey(
                help_text="The student making this lesson request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
