# Generated by Django 5.1.2 on 2024-12-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorials", "0003_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/default.jpg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
