# Generated by Django 5.1.2 on 2024-12-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_month',
            field=models.CharField(default='December', max_length=15),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, default='', help_text='Admins reply to message', null=True),
        ),
    ]
