# Generated by Django 5.1.2 on 2024-11-29 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_invoice_lessonbooking_lessonrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonrequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'Lesson Request', 'verbose_name_plural': 'Lesson Requests'},
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='The tutor assigned to this lesson request. Null if unallocated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Additional information or requests.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the lesson request was created.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_duration',
            field=models.PositiveIntegerField(help_text='Lesson duration in minutes.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_frequency',
            field=models.CharField(help_text='How often would you like your lessons (e.g Weekly, Fortnightly)?', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_time',
            field=models.TimeField(help_text='Preferred time for the lesson.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_topic',
            field=models.TextField(blank=True, help_text='Describe what you would like to learn (e.g Web Development with Django).'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('Unallocated', 'Unallocated'), ('Allocated', 'Allocated'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Unallocated', help_text='The current status of the lesson request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='student',
            field=models.ForeignKey(help_text='The student making the lesson request.', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
