# Generated by Django 5.1.2 on 2024-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_lessonrequest_requested_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='preferred_day',
        ),
        migrations.RemoveField(
            model_name='lessonrequest',
            name='requested_month',
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_date',
            field=models.DateField(blank=True, help_text='Select the date for your lesson.', null=True),
        ),
    ]
