# Generated by Django 5.1.2 on 2024-12-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_alter_lessonrequest_options_lessonrequest_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbooking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='experience_level',
            field=models.CharField(default='no_experience', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='frequency',
            field=models.CharField(default='weekly', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonbooking',
            name='preferred_day',
            field=models.CharField(default='Monday', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessonbooking',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
