# Generated by Django 5.1.2 on 2024-12-01 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_lessonbooking_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbooking',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_lessons', to=settings.AUTH_USER_MODEL),
        ),
    ]
