# Generated by Django 5.1.2 on 2024-12-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_remove_lessonrequest_preferred_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonbooking',
            name='student',
        ),
        migrations.RemoveField(
            model_name='lessonbooking',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='student',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='experience_level',
            field=models.TextField(choices=[('no_experience', 'No Experience'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='No Experience', help_text='Describe your level of experience with this topic.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_date',
            field=models.DateField(default='2024-01-01', help_text='Select the date for your lesson.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_duration',
            field=models.PositiveIntegerField(choices=[(30, '30 Minutes'), (60, '1 Hour'), (90, '1 Hour and 30 Minutes'), (120, '2 Hours')], default=60, help_text='Lesson duration in minutes.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly')], default='Weekly', help_text='How often would you like your lessons (e.g Weekly, Fortnightly)?', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_topic',
            field=models.TextField(choices=[('python_programming', 'Python Programming'), ('web_development_with_js', 'Web Development with JavaScript'), ('ruby_on_rails', 'Ruby on Rails'), ('ai_and_ml', 'AI and Machine Learning')], default='Python Programming', help_text='Describe what you would like to learn (e.g Web Development with Django).'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonBooking',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
