# Generated by Django 5.1.2 on 2024-12-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_alter_lessonbooking_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='preferred_day',
            field=models.CharField(default='Monday', help_text='Preferred day for the lesson.', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='additional_notes',
            field=models.TextField(blank=True, default='', help_text='Additional information or requests.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='experience_level',
            field=models.TextField(default='No Experience', help_text='Describe your level of experience with this topic.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_duration',
            field=models.PositiveIntegerField(default=60, help_text='Lesson duration in minutes.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_frequency',
            field=models.CharField(default='Weekly', help_text='How often would you like your lessons (e.g Weekly, Fortnightly)?', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_time',
            field=models.TimeField(default='09:00:00', help_text='Preferred time for the lesson.'),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='requested_topic',
            field=models.TextField(blank=True, default='Python Programming', help_text='Describe what you would like to learn (e.g Web Development with Django).'),
        ),
    ]
