# Generated by Django 5.1.2 on 2024-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_lessonrequest_preferred_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Write your message to the admin here')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('Unallocated', 'Unallocated'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled')], default='Unallocated', help_text='The current status of the lesson request.', max_length=20),
        ),
    ]
