# Generated by Django 5.1.2 on 2024-12-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_lessonrequest_preferred_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
