# Generated by Django 5.1.2 on 2024-12-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_date',
            field=models.DateField(blank=True, help_text='Select the date for your lesson.', null=True),
        ),
        migrations.AlterField(
            model_name='lessonrequest',
            name='status',
            field=models.CharField(choices=[('Unallocated', 'Unallocated'), ('Allocated', 'Allocated'), ('Cancelled', 'Cancelled')], default='Unallocated', help_text='The current status of the lesson request.', max_length=20),
        ),
    ]
