# Generated by Django 5.1.2 on 2024-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_alter_contactmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, default='', help_text='Admins reply to message'),
        ),
    ]
